// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: proto/master_server.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	primitive "quark/proto/primitive"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterGameServerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewGameServer *primitive.GameServer `protobuf:"bytes,1,opt,name=newGameServer,proto3" json:"newGameServer,omitempty"`
}

func (x *RegisterGameServerRequest) Reset() {
	*x = RegisterGameServerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_master_server_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterGameServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterGameServerRequest) ProtoMessage() {}

func (x *RegisterGameServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_master_server_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterGameServerRequest.ProtoReflect.Descriptor instead.
func (*RegisterGameServerRequest) Descriptor() ([]byte, []int) {
	return file_proto_master_server_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterGameServerRequest) GetNewGameServer() *primitive.GameServer {
	if x != nil {
		return x.NewGameServer
	}
	return nil
}

type MasterServerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Message:
	//	*MasterServerMessage_Registered
	//	*MasterServerMessage_Allocation
	Message isMasterServerMessage_Message `protobuf_oneof:"message"`
}

func (x *MasterServerMessage) Reset() {
	*x = MasterServerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_master_server_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MasterServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterServerMessage) ProtoMessage() {}

func (x *MasterServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_master_server_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterServerMessage.ProtoReflect.Descriptor instead.
func (*MasterServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_master_server_proto_rawDescGZIP(), []int{1}
}

func (m *MasterServerMessage) GetMessage() isMasterServerMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (x *MasterServerMessage) GetRegistered() *MasterServerMessage_GameServerRegistered {
	if x, ok := x.GetMessage().(*MasterServerMessage_Registered); ok {
		return x.Registered
	}
	return nil
}

func (x *MasterServerMessage) GetAllocation() *MasterServerMessage_RoomAllocation {
	if x, ok := x.GetMessage().(*MasterServerMessage_Allocation); ok {
		return x.Allocation
	}
	return nil
}

type isMasterServerMessage_Message interface {
	isMasterServerMessage_Message()
}

type MasterServerMessage_Registered struct {
	Registered *MasterServerMessage_GameServerRegistered `protobuf:"bytes,1,opt,name=registered,proto3,oneof"`
}

type MasterServerMessage_Allocation struct {
	Allocation *MasterServerMessage_RoomAllocation `protobuf:"bytes,2,opt,name=allocation,proto3,oneof"`
}

func (*MasterServerMessage_Registered) isMasterServerMessage_Message() {}

func (*MasterServerMessage_Allocation) isMasterServerMessage_Message() {}

type GameServerStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UpdateRoomState []*GameServerStatus_RoomState `protobuf:"bytes,1,rep,name=updateRoomState,proto3" json:"updateRoomState,omitempty"`
}

func (x *GameServerStatus) Reset() {
	*x = GameServerStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_master_server_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameServerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameServerStatus) ProtoMessage() {}

func (x *GameServerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_master_server_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameServerStatus.ProtoReflect.Descriptor instead.
func (*GameServerStatus) Descriptor() ([]byte, []int) {
	return file_proto_master_server_proto_rawDescGZIP(), []int{2}
}

func (x *GameServerStatus) GetUpdateRoomState() []*GameServerStatus_RoomState {
	if x != nil {
		return x.UpdateRoomState
	}
	return nil
}

type MasterServerMessage_GameServerRegistered struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GameServerID string `protobuf:"bytes,1,opt,name=gameServerID,proto3" json:"gameServerID,omitempty"`
}

func (x *MasterServerMessage_GameServerRegistered) Reset() {
	*x = MasterServerMessage_GameServerRegistered{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_master_server_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MasterServerMessage_GameServerRegistered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterServerMessage_GameServerRegistered) ProtoMessage() {}

func (x *MasterServerMessage_GameServerRegistered) ProtoReflect() protoreflect.Message {
	mi := &file_proto_master_server_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterServerMessage_GameServerRegistered.ProtoReflect.Descriptor instead.
func (*MasterServerMessage_GameServerRegistered) Descriptor() ([]byte, []int) {
	return file_proto_master_server_proto_rawDescGZIP(), []int{1, 0}
}

func (x *MasterServerMessage_GameServerRegistered) GetGameServerID() string {
	if x != nil {
		return x.GameServerID
	}
	return ""
}

type MasterServerMessage_RoomAllocation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Room *primitive.Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
}

func (x *MasterServerMessage_RoomAllocation) Reset() {
	*x = MasterServerMessage_RoomAllocation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_master_server_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MasterServerMessage_RoomAllocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MasterServerMessage_RoomAllocation) ProtoMessage() {}

func (x *MasterServerMessage_RoomAllocation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_master_server_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MasterServerMessage_RoomAllocation.ProtoReflect.Descriptor instead.
func (*MasterServerMessage_RoomAllocation) Descriptor() ([]byte, []int) {
	return file_proto_master_server_proto_rawDescGZIP(), []int{1, 1}
}

func (x *MasterServerMessage_RoomAllocation) GetRoom() *primitive.Room {
	if x != nil {
		return x.Room
	}
	return nil
}

type GameServerStatus_RoomState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Room       *primitive.Room `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	ActorCount uint64          `protobuf:"varint,2,opt,name=actorCount,proto3" json:"actorCount,omitempty"`
}

func (x *GameServerStatus_RoomState) Reset() {
	*x = GameServerStatus_RoomState{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_master_server_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameServerStatus_RoomState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameServerStatus_RoomState) ProtoMessage() {}

func (x *GameServerStatus_RoomState) ProtoReflect() protoreflect.Message {
	mi := &file_proto_master_server_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameServerStatus_RoomState.ProtoReflect.Descriptor instead.
func (*GameServerStatus_RoomState) Descriptor() ([]byte, []int) {
	return file_proto_master_server_proto_rawDescGZIP(), []int{2, 0}
}

func (x *GameServerStatus_RoomState) GetRoom() *primitive.Room {
	if x != nil {
		return x.Room
	}
	return nil
}

func (x *GameServerStatus_RoomState) GetActorCount() uint64 {
	if x != nil {
		return x.ActorCount
	}
	return 0
}

var File_proto_master_server_proto protoreflect.FileDescriptor

var file_proto_master_server_proto_rawDesc = []byte{
	0x0a, 0x19, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x71, 0x75, 0x61,
	0x72, 0x6b, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x21, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65,
	0x2f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x72, 0x69, 0x6d, 0x69, 0x74,
	0x69, 0x76, 0x65, 0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5e,
	0x0a, 0x19, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x41, 0x0a, 0x0d, 0x6e,
	0x65, 0x77, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x71, 0x75, 0x61, 0x72, 0x6b, 0x2e, 0x70, 0x72, 0x69, 0x6d, 0x69,
	0x74, 0x69, 0x76, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52,
	0x0d, 0x6e, 0x65, 0x77, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x22, 0xb9,
	0x02, 0x0a, 0x13, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x51, 0x0a, 0x0a, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x71, 0x75, 0x61,
	0x72, 0x6b, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x48, 0x00, 0x52, 0x0a, 0x72,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x12, 0x4b, 0x0a, 0x0a, 0x61, 0x6c, 0x6c,
	0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e,
	0x71, 0x75, 0x61, 0x72, 0x6b, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x41, 0x6c,
	0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0a, 0x61, 0x6c, 0x6c, 0x6f,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x3a, 0x0a, 0x14, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x12, 0x22,
	0x0a, 0x0c, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x49, 0x44, 0x1a, 0x3b, 0x0a, 0x0e, 0x52, 0x6f, 0x6f, 0x6d, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x71, 0x75, 0x61, 0x72, 0x6b, 0x2e, 0x70, 0x72, 0x69, 0x6d, 0x69,
	0x74, 0x69, 0x76, 0x65, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x04, 0x72, 0x6f, 0x6f, 0x6d, 0x42,
	0x09, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0xb7, 0x01, 0x0a, 0x10, 0x47,
	0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x4b, 0x0a, 0x0f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x71, 0x75, 0x61, 0x72, 0x6b,
	0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x0f, 0x75, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x1a, 0x56, 0x0a, 0x09,
	0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x29, 0x0a, 0x04, 0x72, 0x6f, 0x6f,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x71, 0x75, 0x61, 0x72, 0x6b, 0x2e,
	0x70, 0x72, 0x69, 0x6d, 0x69, 0x74, 0x69, 0x76, 0x65, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x04,
	0x72, 0x6f, 0x6f, 0x6d, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x32, 0xa1, 0x01, 0x0a, 0x0c, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x54, 0x0a, 0x12, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x20, 0x2e, 0x71, 0x75,
	0x61, 0x72, 0x6b, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x47, 0x61, 0x6d, 0x65,
	0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e,
	0x71, 0x75, 0x61, 0x72, 0x6b, 0x2e, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x30, 0x01, 0x12, 0x3b, 0x0a, 0x06, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x71, 0x75, 0x61, 0x72, 0x6b, 0x2e, 0x47, 0x61,
	0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x28, 0x01, 0x42, 0x0d, 0x5a, 0x0b, 0x71, 0x75, 0x61, 0x72,
	0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_master_server_proto_rawDescOnce sync.Once
	file_proto_master_server_proto_rawDescData = file_proto_master_server_proto_rawDesc
)

func file_proto_master_server_proto_rawDescGZIP() []byte {
	file_proto_master_server_proto_rawDescOnce.Do(func() {
		file_proto_master_server_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_master_server_proto_rawDescData)
	})
	return file_proto_master_server_proto_rawDescData
}

var file_proto_master_server_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_master_server_proto_goTypes = []interface{}{
	(*RegisterGameServerRequest)(nil),                // 0: quark.RegisterGameServerRequest
	(*MasterServerMessage)(nil),                      // 1: quark.MasterServerMessage
	(*GameServerStatus)(nil),                         // 2: quark.GameServerStatus
	(*MasterServerMessage_GameServerRegistered)(nil), // 3: quark.MasterServerMessage.GameServerRegistered
	(*MasterServerMessage_RoomAllocation)(nil),       // 4: quark.MasterServerMessage.RoomAllocation
	(*GameServerStatus_RoomState)(nil),               // 5: quark.GameServerStatus.RoomState
	(*primitive.GameServer)(nil),                     // 6: quark.primitive.GameServer
	(*primitive.Room)(nil),                           // 7: quark.primitive.Room
	(*emptypb.Empty)(nil),                            // 8: google.protobuf.Empty
}
var file_proto_master_server_proto_depIdxs = []int32{
	6, // 0: quark.RegisterGameServerRequest.newGameServer:type_name -> quark.primitive.GameServer
	3, // 1: quark.MasterServerMessage.registered:type_name -> quark.MasterServerMessage.GameServerRegistered
	4, // 2: quark.MasterServerMessage.allocation:type_name -> quark.MasterServerMessage.RoomAllocation
	5, // 3: quark.GameServerStatus.updateRoomState:type_name -> quark.GameServerStatus.RoomState
	7, // 4: quark.MasterServerMessage.RoomAllocation.room:type_name -> quark.primitive.Room
	7, // 5: quark.GameServerStatus.RoomState.room:type_name -> quark.primitive.Room
	0, // 6: quark.MasterServer.RegisterGameServer:input_type -> quark.RegisterGameServerRequest
	2, // 7: quark.MasterServer.Update:input_type -> quark.GameServerStatus
	1, // 8: quark.MasterServer.RegisterGameServer:output_type -> quark.MasterServerMessage
	8, // 9: quark.MasterServer.Update:output_type -> google.protobuf.Empty
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_proto_master_server_proto_init() }
func file_proto_master_server_proto_init() {
	if File_proto_master_server_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_master_server_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterGameServerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_master_server_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MasterServerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_master_server_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameServerStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_master_server_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MasterServerMessage_GameServerRegistered); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_master_server_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MasterServerMessage_RoomAllocation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_master_server_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameServerStatus_RoomState); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_master_server_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*MasterServerMessage_Registered)(nil),
		(*MasterServerMessage_Allocation)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_master_server_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_master_server_proto_goTypes,
		DependencyIndexes: file_proto_master_server_proto_depIdxs,
		MessageInfos:      file_proto_master_server_proto_msgTypes,
	}.Build()
	File_proto_master_server_proto = out.File
	file_proto_master_server_proto_rawDesc = nil
	file_proto_master_server_proto_goTypes = nil
	file_proto_master_server_proto_depIdxs = nil
}
