// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: proto/room.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRoomRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomName string `protobuf:"bytes,1,opt,name=roomName,proto3" json:"roomName,omitempty"`
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_room_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoomRequest) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID       uint64 `protobuf:"varint,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
	AlreadyExist bool   `protobuf:"varint,2,opt,name=alreadyExist,proto3" json:"alreadyExist,omitempty"`
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_room_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoomResponse) GetRoomID() uint64 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

func (x *CreateRoomResponse) GetAlreadyExist() bool {
	if x != nil {
		return x.AlreadyExist
	}
	return false
}

type ClientMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Command:
	//	*ClientMessage_JoinRoom
	//	*ClientMessage_SendMessage
	//	*ClientMessage_LeaveRoom
	Command isClientMessage_Command `protobuf_oneof:"command"`
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_proto_room_proto_rawDescGZIP(), []int{2}
}

func (m *ClientMessage) GetCommand() isClientMessage_Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func (x *ClientMessage) GetJoinRoom() *ClientMessage_JoinRoomCommand {
	if x, ok := x.GetCommand().(*ClientMessage_JoinRoom); ok {
		return x.JoinRoom
	}
	return nil
}

func (x *ClientMessage) GetSendMessage() *ClientMessage_SendMessageCommand {
	if x, ok := x.GetCommand().(*ClientMessage_SendMessage); ok {
		return x.SendMessage
	}
	return nil
}

func (x *ClientMessage) GetLeaveRoom() *ClientMessage_LeaveRoomCommand {
	if x, ok := x.GetCommand().(*ClientMessage_LeaveRoom); ok {
		return x.LeaveRoom
	}
	return nil
}

type isClientMessage_Command interface {
	isClientMessage_Command()
}

type ClientMessage_JoinRoom struct {
	JoinRoom *ClientMessage_JoinRoomCommand `protobuf:"bytes,1,opt,name=joinRoom,proto3,oneof"`
}

type ClientMessage_SendMessage struct {
	SendMessage *ClientMessage_SendMessageCommand `protobuf:"bytes,2,opt,name=sendMessage,proto3,oneof"`
}

type ClientMessage_LeaveRoom struct {
	LeaveRoom *ClientMessage_LeaveRoomCommand `protobuf:"bytes,3,opt,name=leaveRoom,proto3,oneof"`
}

func (*ClientMessage_JoinRoom) isClientMessage_Command() {}

func (*ClientMessage_SendMessage) isClientMessage_Command() {}

func (*ClientMessage_LeaveRoom) isClientMessage_Command() {}

type Message struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    uint32 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Payload []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *Message) Reset() {
	*x = Message{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_room_proto_rawDescGZIP(), []int{3}
}

func (x *Message) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ServerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//	*ServerMessage_OnCommandFailed
	//	*ServerMessage_OnJoinRoomSuccess
	//	*ServerMessage_OnLeaveRoomSuccess
	//	*ServerMessage_OnMessageReceived
	//	*ServerMessage_OnJoinRoom
	Event isServerMessage_Event `protobuf_oneof:"event"`
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_proto_room_proto_rawDescGZIP(), []int{4}
}

func (m *ServerMessage) GetEvent() isServerMessage_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *ServerMessage) GetOnCommandFailed() *ServerMessage_CommandError {
	if x, ok := x.GetEvent().(*ServerMessage_OnCommandFailed); ok {
		return x.OnCommandFailed
	}
	return nil
}

func (x *ServerMessage) GetOnJoinRoomSuccess() *ServerMessage_JoinRoomSuccess {
	if x, ok := x.GetEvent().(*ServerMessage_OnJoinRoomSuccess); ok {
		return x.OnJoinRoomSuccess
	}
	return nil
}

func (x *ServerMessage) GetOnLeaveRoomSuccess() *ServerMessage_LeaveRoomSuccess {
	if x, ok := x.GetEvent().(*ServerMessage_OnLeaveRoomSuccess); ok {
		return x.OnLeaveRoomSuccess
	}
	return nil
}

func (x *ServerMessage) GetOnMessageReceived() *ServerMessage_ReceivedMessageEvent {
	if x, ok := x.GetEvent().(*ServerMessage_OnMessageReceived); ok {
		return x.OnMessageReceived
	}
	return nil
}

func (x *ServerMessage) GetOnJoinRoom() *ServerMessage_JoinRoom {
	if x, ok := x.GetEvent().(*ServerMessage_OnJoinRoom); ok {
		return x.OnJoinRoom
	}
	return nil
}

type isServerMessage_Event interface {
	isServerMessage_Event()
}

type ServerMessage_OnCommandFailed struct {
	// command result
	OnCommandFailed *ServerMessage_CommandError `protobuf:"bytes,1,opt,name=onCommandFailed,proto3,oneof"`
}

type ServerMessage_OnJoinRoomSuccess struct {
	OnJoinRoomSuccess *ServerMessage_JoinRoomSuccess `protobuf:"bytes,2,opt,name=onJoinRoomSuccess,proto3,oneof"`
}

type ServerMessage_OnLeaveRoomSuccess struct {
	OnLeaveRoomSuccess *ServerMessage_LeaveRoomSuccess `protobuf:"bytes,3,opt,name=onLeaveRoomSuccess,proto3,oneof"`
}

type ServerMessage_OnMessageReceived struct {
	OnMessageReceived *ServerMessage_ReceivedMessageEvent `protobuf:"bytes,4,opt,name=onMessageReceived,proto3,oneof"`
}

type ServerMessage_OnJoinRoom struct {
	OnJoinRoom *ServerMessage_JoinRoom `protobuf:"bytes,5,opt,name=onJoinRoom,proto3,oneof"`
}

func (*ServerMessage_OnCommandFailed) isServerMessage_Event() {}

func (*ServerMessage_OnJoinRoomSuccess) isServerMessage_Event() {}

func (*ServerMessage_OnLeaveRoomSuccess) isServerMessage_Event() {}

func (*ServerMessage_OnMessageReceived) isServerMessage_Event() {}

func (*ServerMessage_OnJoinRoom) isServerMessage_Event() {}

type ClientMessage_JoinRoomCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomID uint64 `protobuf:"varint,1,opt,name=roomID,proto3" json:"roomID,omitempty"`
}

func (x *ClientMessage_JoinRoomCommand) Reset() {
	*x = ClientMessage_JoinRoomCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_JoinRoomCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_JoinRoomCommand) ProtoMessage() {}

func (x *ClientMessage_JoinRoomCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_JoinRoomCommand.ProtoReflect.Descriptor instead.
func (*ClientMessage_JoinRoomCommand) Descriptor() ([]byte, []int) {
	return file_proto_room_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ClientMessage_JoinRoomCommand) GetRoomID() uint64 {
	if x != nil {
		return x.RoomID
	}
	return 0
}

type ClientMessage_SendMessageCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *ClientMessage_SendMessageCommand) Reset() {
	*x = ClientMessage_SendMessageCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_SendMessageCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_SendMessageCommand) ProtoMessage() {}

func (x *ClientMessage_SendMessageCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_SendMessageCommand.ProtoReflect.Descriptor instead.
func (*ClientMessage_SendMessageCommand) Descriptor() ([]byte, []int) {
	return file_proto_room_proto_rawDescGZIP(), []int{2, 1}
}

func (x *ClientMessage_SendMessageCommand) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type ClientMessage_LeaveRoomCommand struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClientMessage_LeaveRoomCommand) Reset() {
	*x = ClientMessage_LeaveRoomCommand{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage_LeaveRoomCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage_LeaveRoomCommand) ProtoMessage() {}

func (x *ClientMessage_LeaveRoomCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage_LeaveRoomCommand.ProtoReflect.Descriptor instead.
func (*ClientMessage_LeaveRoomCommand) Descriptor() ([]byte, []int) {
	return file_proto_room_proto_rawDescGZIP(), []int{2, 2}
}

type ServerMessage_CommandError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorCode   string `protobuf:"bytes,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	ErrorDetail string `protobuf:"bytes,2,opt,name=errorDetail,proto3" json:"errorDetail,omitempty"`
	// Types that are assignable to ErrorCommand:
	//	*ServerMessage_CommandError_JoinRoom
	//	*ServerMessage_CommandError_SendMessage
	//	*ServerMessage_CommandError_LeaveRoom
	ErrorCommand isServerMessage_CommandError_ErrorCommand `protobuf_oneof:"errorCommand"`
}

func (x *ServerMessage_CommandError) Reset() {
	*x = ServerMessage_CommandError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage_CommandError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage_CommandError) ProtoMessage() {}

func (x *ServerMessage_CommandError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage_CommandError.ProtoReflect.Descriptor instead.
func (*ServerMessage_CommandError) Descriptor() ([]byte, []int) {
	return file_proto_room_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ServerMessage_CommandError) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *ServerMessage_CommandError) GetErrorDetail() string {
	if x != nil {
		return x.ErrorDetail
	}
	return ""
}

func (m *ServerMessage_CommandError) GetErrorCommand() isServerMessage_CommandError_ErrorCommand {
	if m != nil {
		return m.ErrorCommand
	}
	return nil
}

func (x *ServerMessage_CommandError) GetJoinRoom() *ClientMessage_JoinRoomCommand {
	if x, ok := x.GetErrorCommand().(*ServerMessage_CommandError_JoinRoom); ok {
		return x.JoinRoom
	}
	return nil
}

func (x *ServerMessage_CommandError) GetSendMessage() *ClientMessage_SendMessageCommand {
	if x, ok := x.GetErrorCommand().(*ServerMessage_CommandError_SendMessage); ok {
		return x.SendMessage
	}
	return nil
}

func (x *ServerMessage_CommandError) GetLeaveRoom() *ClientMessage_LeaveRoomCommand {
	if x, ok := x.GetErrorCommand().(*ServerMessage_CommandError_LeaveRoom); ok {
		return x.LeaveRoom
	}
	return nil
}

type isServerMessage_CommandError_ErrorCommand interface {
	isServerMessage_CommandError_ErrorCommand()
}

type ServerMessage_CommandError_JoinRoom struct {
	JoinRoom *ClientMessage_JoinRoomCommand `protobuf:"bytes,3,opt,name=joinRoom,proto3,oneof"`
}

type ServerMessage_CommandError_SendMessage struct {
	SendMessage *ClientMessage_SendMessageCommand `protobuf:"bytes,4,opt,name=sendMessage,proto3,oneof"`
}

type ServerMessage_CommandError_LeaveRoom struct {
	LeaveRoom *ClientMessage_LeaveRoomCommand `protobuf:"bytes,5,opt,name=leaveRoom,proto3,oneof"`
}

func (*ServerMessage_CommandError_JoinRoom) isServerMessage_CommandError_ErrorCommand() {}

func (*ServerMessage_CommandError_SendMessage) isServerMessage_CommandError_ErrorCommand() {}

func (*ServerMessage_CommandError_LeaveRoom) isServerMessage_CommandError_ErrorCommand() {}

type ServerMessage_JoinRoomSuccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorID string `protobuf:"bytes,1,opt,name=actorID,proto3" json:"actorID,omitempty"`
}

func (x *ServerMessage_JoinRoomSuccess) Reset() {
	*x = ServerMessage_JoinRoomSuccess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage_JoinRoomSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage_JoinRoomSuccess) ProtoMessage() {}

func (x *ServerMessage_JoinRoomSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage_JoinRoomSuccess.ProtoReflect.Descriptor instead.
func (*ServerMessage_JoinRoomSuccess) Descriptor() ([]byte, []int) {
	return file_proto_room_proto_rawDescGZIP(), []int{4, 1}
}

func (x *ServerMessage_JoinRoomSuccess) GetActorID() string {
	if x != nil {
		return x.ActorID
	}
	return ""
}

type ServerMessage_LeaveRoomSuccess struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ServerMessage_LeaveRoomSuccess) Reset() {
	*x = ServerMessage_LeaveRoomSuccess{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage_LeaveRoomSuccess) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage_LeaveRoomSuccess) ProtoMessage() {}

func (x *ServerMessage_LeaveRoomSuccess) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage_LeaveRoomSuccess.ProtoReflect.Descriptor instead.
func (*ServerMessage_LeaveRoomSuccess) Descriptor() ([]byte, []int) {
	return file_proto_room_proto_rawDescGZIP(), []int{4, 2}
}

type ServerMessage_ReceivedMessageEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message  *Message `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	SenderID string   `protobuf:"bytes,2,opt,name=senderID,proto3" json:"senderID,omitempty"`
}

func (x *ServerMessage_ReceivedMessageEvent) Reset() {
	*x = ServerMessage_ReceivedMessageEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage_ReceivedMessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage_ReceivedMessageEvent) ProtoMessage() {}

func (x *ServerMessage_ReceivedMessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage_ReceivedMessageEvent.ProtoReflect.Descriptor instead.
func (*ServerMessage_ReceivedMessageEvent) Descriptor() ([]byte, []int) {
	return file_proto_room_proto_rawDescGZIP(), []int{4, 3}
}

func (x *ServerMessage_ReceivedMessageEvent) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerMessage_ReceivedMessageEvent) GetSenderID() string {
	if x != nil {
		return x.SenderID
	}
	return ""
}

type ServerMessage_JoinRoom struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ActorIDList []string `protobuf:"bytes,1,rep,name=actorIDList,proto3" json:"actorIDList,omitempty"`
	NewActorID  string   `protobuf:"bytes,2,opt,name=newActorID,proto3" json:"newActorID,omitempty"`
}

func (x *ServerMessage_JoinRoom) Reset() {
	*x = ServerMessage_JoinRoom{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_room_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage_JoinRoom) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage_JoinRoom) ProtoMessage() {}

func (x *ServerMessage_JoinRoom) ProtoReflect() protoreflect.Message {
	mi := &file_proto_room_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage_JoinRoom.ProtoReflect.Descriptor instead.
func (*ServerMessage_JoinRoom) Descriptor() ([]byte, []int) {
	return file_proto_room_proto_rawDescGZIP(), []int{4, 4}
}

func (x *ServerMessage_JoinRoom) GetActorIDList() []string {
	if x != nil {
		return x.ActorIDList
	}
	return nil
}

func (x *ServerMessage_JoinRoom) GetNewActorID() string {
	if x != nil {
		return x.NewActorID
	}
	return ""
}

var File_proto_room_proto protoreflect.FileDescriptor

var file_proto_room_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x71, 0x75, 0x61, 0x72, 0x6b, 0x22, 0x2f, 0x0a, 0x11, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x72, 0x6f, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x50, 0x0a, 0x12, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x6c, 0x72, 0x65,
	0x61, 0x64, 0x79, 0x45, 0x78, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c,
	0x61, 0x6c, 0x72, 0x65, 0x61, 0x64, 0x79, 0x45, 0x78, 0x69, 0x73, 0x74, 0x22, 0xf1, 0x02, 0x0a,
	0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x42,
	0x0a, 0x08, 0x6a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x24, 0x2e, 0x71, 0x75, 0x61, 0x72, 0x6b, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x43,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x08, 0x6a, 0x6f, 0x69, 0x6e, 0x52, 0x6f,
	0x6f, 0x6d, 0x12, 0x4b, 0x0a, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x71, 0x75, 0x61, 0x72, 0x6b, 0x2e,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x65,
	0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x48, 0x00, 0x52, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x45, 0x0a, 0x09, 0x6c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x25, 0x2e, 0x71, 0x75, 0x61, 0x72, 0x6b, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x09, 0x6c, 0x65, 0x61,
	0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x1a, 0x29, 0x0a, 0x0f, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f,
	0x6f, 0x6d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6f,
	0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49,
	0x44, 0x1a, 0x3e, 0x0a, 0x12, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x28, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x71, 0x75, 0x61, 0x72, 0x6b,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x1a, 0x12, 0x0a, 0x10, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x6f,
	0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64,
	0x22, 0x37, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xd8, 0x07, 0x0a, 0x0d, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x4d, 0x0a, 0x0f, 0x6f,
	0x6e, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x71, 0x75, 0x61, 0x72, 0x6b, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x61,
	0x6e, 0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x0f, 0x6f, 0x6e, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x12, 0x54, 0x0a, 0x11, 0x6f, 0x6e,
	0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x71, 0x75, 0x61, 0x72, 0x6b, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4a, 0x6f, 0x69, 0x6e,
	0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x48, 0x00, 0x52, 0x11, 0x6f,
	0x6e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x12, 0x57, 0x0a, 0x12, 0x6f, 0x6e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x71,
	0x75, 0x61, 0x72, 0x6b, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x2e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x48, 0x00, 0x52, 0x12, 0x6f, 0x6e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x6f,
	0x6f, 0x6d, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x59, 0x0a, 0x11, 0x6f, 0x6e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x71, 0x75, 0x61, 0x72, 0x6b, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48,
	0x00, 0x52, 0x11, 0x6f, 0x6e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x64, 0x12, 0x3f, 0x0a, 0x0a, 0x6f, 0x6e, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f,
	0x6f, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x71, 0x75, 0x61, 0x72, 0x6b,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4a,
	0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x48, 0x00, 0x52, 0x0a, 0x6f, 0x6e, 0x4a, 0x6f, 0x69,
	0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x1a, 0xb6, 0x02, 0x0a, 0x0c, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x42, 0x0a, 0x08, 0x6a, 0x6f, 0x69, 0x6e, 0x52, 0x6f,
	0x6f, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x71, 0x75, 0x61, 0x72, 0x6b,
	0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x4a,
	0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00,
	0x52, 0x08, 0x6a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x4b, 0x0a, 0x0b, 0x73, 0x65,
	0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x27, 0x2e, 0x71, 0x75, 0x61, 0x72, 0x6b, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x65, 0x6e, 0x64,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x45, 0x0a, 0x09, 0x6c, 0x65, 0x61, 0x76, 0x65,
	0x52, 0x6f, 0x6f, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x71, 0x75, 0x61,
	0x72, 0x6b, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x4c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e,
	0x64, 0x48, 0x00, 0x52, 0x09, 0x6c, 0x65, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x42, 0x0e,
	0x0a, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x1a, 0x2b,
	0x0a, 0x0f, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x1a, 0x12, 0x0a, 0x10, 0x4c,
	0x65, 0x61, 0x76, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x1a,
	0x5c, 0x0a, 0x14, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x28, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x71, 0x75, 0x61, 0x72, 0x6b,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x44, 0x1a, 0x4c, 0x0a,
	0x08, 0x4a, 0x6f, 0x69, 0x6e, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x74,
	0x6f, 0x72, 0x49, 0x44, 0x4c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b,
	0x61, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x6e,
	0x65, 0x77, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x6e, 0x65, 0x77, 0x41, 0x63, 0x74, 0x6f, 0x72, 0x49, 0x44, 0x42, 0x07, 0x0a, 0x05, 0x65,
	0x76, 0x65, 0x6e, 0x74, 0x32, 0x84, 0x01, 0x0a, 0x04, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x41, 0x0a,
	0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x12, 0x18, 0x2e, 0x71, 0x75,
	0x61, 0x72, 0x6b, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x71, 0x75, 0x61, 0x72, 0x6b, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x39, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x14, 0x2e, 0x71, 0x75,
	0x61, 0x72, 0x6b, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x1a, 0x14, 0x2e, 0x71, 0x75, 0x61, 0x72, 0x6b, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0d, 0x5a, 0x0b, 0x71,
	0x75, 0x61, 0x72, 0x6b, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_proto_room_proto_rawDescOnce sync.Once
	file_proto_room_proto_rawDescData = file_proto_room_proto_rawDesc
)

func file_proto_room_proto_rawDescGZIP() []byte {
	file_proto_room_proto_rawDescOnce.Do(func() {
		file_proto_room_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_room_proto_rawDescData)
	})
	return file_proto_room_proto_rawDescData
}

var file_proto_room_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_room_proto_goTypes = []interface{}{
	(*CreateRoomRequest)(nil),                  // 0: quark.CreateRoomRequest
	(*CreateRoomResponse)(nil),                 // 1: quark.CreateRoomResponse
	(*ClientMessage)(nil),                      // 2: quark.ClientMessage
	(*Message)(nil),                            // 3: quark.Message
	(*ServerMessage)(nil),                      // 4: quark.ServerMessage
	(*ClientMessage_JoinRoomCommand)(nil),      // 5: quark.ClientMessage.JoinRoomCommand
	(*ClientMessage_SendMessageCommand)(nil),   // 6: quark.ClientMessage.SendMessageCommand
	(*ClientMessage_LeaveRoomCommand)(nil),     // 7: quark.ClientMessage.LeaveRoomCommand
	(*ServerMessage_CommandError)(nil),         // 8: quark.ServerMessage.CommandError
	(*ServerMessage_JoinRoomSuccess)(nil),      // 9: quark.ServerMessage.JoinRoomSuccess
	(*ServerMessage_LeaveRoomSuccess)(nil),     // 10: quark.ServerMessage.LeaveRoomSuccess
	(*ServerMessage_ReceivedMessageEvent)(nil), // 11: quark.ServerMessage.ReceivedMessageEvent
	(*ServerMessage_JoinRoom)(nil),             // 12: quark.ServerMessage.JoinRoom
}
var file_proto_room_proto_depIdxs = []int32{
	5,  // 0: quark.ClientMessage.joinRoom:type_name -> quark.ClientMessage.JoinRoomCommand
	6,  // 1: quark.ClientMessage.sendMessage:type_name -> quark.ClientMessage.SendMessageCommand
	7,  // 2: quark.ClientMessage.leaveRoom:type_name -> quark.ClientMessage.LeaveRoomCommand
	8,  // 3: quark.ServerMessage.onCommandFailed:type_name -> quark.ServerMessage.CommandError
	9,  // 4: quark.ServerMessage.onJoinRoomSuccess:type_name -> quark.ServerMessage.JoinRoomSuccess
	10, // 5: quark.ServerMessage.onLeaveRoomSuccess:type_name -> quark.ServerMessage.LeaveRoomSuccess
	11, // 6: quark.ServerMessage.onMessageReceived:type_name -> quark.ServerMessage.ReceivedMessageEvent
	12, // 7: quark.ServerMessage.onJoinRoom:type_name -> quark.ServerMessage.JoinRoom
	3,  // 8: quark.ClientMessage.SendMessageCommand.message:type_name -> quark.Message
	5,  // 9: quark.ServerMessage.CommandError.joinRoom:type_name -> quark.ClientMessage.JoinRoomCommand
	6,  // 10: quark.ServerMessage.CommandError.sendMessage:type_name -> quark.ClientMessage.SendMessageCommand
	7,  // 11: quark.ServerMessage.CommandError.leaveRoom:type_name -> quark.ClientMessage.LeaveRoomCommand
	3,  // 12: quark.ServerMessage.ReceivedMessageEvent.message:type_name -> quark.Message
	0,  // 13: quark.Room.CreateRoom:input_type -> quark.CreateRoomRequest
	2,  // 14: quark.Room.Service:input_type -> quark.ClientMessage
	1,  // 15: quark.Room.CreateRoom:output_type -> quark.CreateRoomResponse
	4,  // 16: quark.Room.Service:output_type -> quark.ServerMessage
	15, // [15:17] is the sub-list for method output_type
	13, // [13:15] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_room_proto_init() }
func file_proto_room_proto_init() {
	if File_proto_room_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_room_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoomRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRoomResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Message); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_JoinRoomCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_SendMessageCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientMessage_LeaveRoomCommand); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMessage_CommandError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMessage_JoinRoomSuccess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMessage_LeaveRoomSuccess); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMessage_ReceivedMessageEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_room_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServerMessage_JoinRoom); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_room_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*ClientMessage_JoinRoom)(nil),
		(*ClientMessage_SendMessage)(nil),
		(*ClientMessage_LeaveRoom)(nil),
	}
	file_proto_room_proto_msgTypes[4].OneofWrappers = []interface{}{
		(*ServerMessage_OnCommandFailed)(nil),
		(*ServerMessage_OnJoinRoomSuccess)(nil),
		(*ServerMessage_OnLeaveRoomSuccess)(nil),
		(*ServerMessage_OnMessageReceived)(nil),
		(*ServerMessage_OnJoinRoom)(nil),
	}
	file_proto_room_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*ServerMessage_CommandError_JoinRoom)(nil),
		(*ServerMessage_CommandError_SendMessage)(nil),
		(*ServerMessage_CommandError_LeaveRoom)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_room_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_room_proto_goTypes,
		DependencyIndexes: file_proto_room_proto_depIdxs,
		MessageInfos:      file_proto_room_proto_msgTypes,
	}.Build()
	File_proto_room_proto = out.File
	file_proto_room_proto_rawDesc = nil
	file_proto_room_proto_goTypes = nil
	file_proto_room_proto_depIdxs = nil
}
